language: elixir
elixir:
  - '1.7.0'
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - "cp /tmp/cached/mix.lock mix.lock || :"

install:
  # GCC / G++ Setup
  - sudo apt-get install -qq -y gcc-5 g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  # SOLOUD SETUP
  - chmod +x install_soloud.sh
  - ./install_soloud.sh
  # SOLOUDEX SETUP
  - mix local.rebar --force; mix local.hex --force; mix deps.get

before_script:
  - cp mix.lock /tmp/cached/mix.lock

script:
  - mix coveralls && mix credo --strict

cache:
  directories:
  - _build
  - deps
  - priv/lib
  - /tmp/cached
